spring:
  application:
    name: content-loader-adapter
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      batch-size: 16384
      linger-ms: 100
      compression-type: snappy
      acks: all
      retries: 3
      topic: raw-estate-data
server:
  port: 8081
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
logging:
  level:
    com.petrov.content-loader-adapter: DEBUG
    org.springframework.kafka: INFO
