spring:
  application:
    name: notification
  datasource:
    url: jdbc:postgresql://localhost:5432/notification_db
    username: notification_user
    password: notification_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  kafka:
    bootstrap-servers: localhost:29092
    topic:
      main: notifications
      dlt: notifications.DLT
    consumer:
      group-id: notification-group
      trusted-package: com.petrov.notification.dto
      auto-commit: false
      auto-offset-reset: earliest
      max-poll-records: 500
      fetch-max-bytes: 52428800
      properties:
        spring:
          json:
            trusted:
              packages: com.petrov.notification.dto
    producer:
      retries: 3
      acks: all
    listener:
      ack-mode: MANUAL_IMMEDIATE

notification:
  retry:
    max-attempts: 5
    backoff-delay: 2000
    backoff-multiplier: 2
  external:
    sms:
      url: ${SMS_API_URL:https://sms-api.example.com/send}
      timeout: 5000
    email:
      url: ${EMAIL_API_URL:https://email-api.example.com/send}
      timeout: 5000

server:
  port: 8085

logging:
  level:
    com.petrov.notification: DEBUG
    org.springframework.kafka: INFO
    org.springframework.retry: TRACE
    org.hibernate.SQL: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html