apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-processor
  namespace: crm-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content-processor
  template:
    metadata:
      labels:
        app: content-processor
    spec:
      containers:
        - name: content-processor
          image: content-processor:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service:9092"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgresql-history-service:5432/history_db"
            - name: SPRING_DATASOURCE_USERNAME
              value: "history_user"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "history_password"
            - name: KAFKA_TOPIC_RAW_ESTATE_DATA
              value: "raw-estate-data"
            - name: KAFKA_CONSUMER_GROUP_ID
              value: "content-processor-group"
            - name: SERVER_PORT
              value: "8082"
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 90
            periodSeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8082
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: content-processor-service
  namespace: crm-system
spec:
  selector:
    app: content-processor
  ports:
    - port: 8082
      targetPort: 8082
  type: ClusterIP