apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-loader-adapter
  namespace: crm-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content-loader-adapter
  template:
    metadata:
      labels:
        app: content-loader-adapter
    spec:
      containers:
        - name: content-loader-adapter
          image: content-loader-adapter:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service:9092"
            - name: SERVER_PORT
              value: "8081"
            - name: KAFKA_TOPIC_RAW_ESTATE_DATA
              value: "raw-estate-data"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: content-loader-adapter-service
  namespace: crm-system
spec:
  selector:
    app: content-loader-adapter
  ports:
    - port: 8081
      targetPort: 8081
  type: ClusterIP