apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-crm
  namespace: crm-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core-crm
  template:
    metadata:
      labels:
        app: core-crm
    spec:
      containers:
        - name: core-crm
          image: core-crm:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgresql-crm-service:5432/crm_db"
            - name: SPRING_DATASOURCE_USERNAME
              value: "crm_user"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "crm_password"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service:9092"
            - name: SERVER_PORT
              value: "8084"
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            initialDelaySeconds: 90
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8084
            initialDelaySeconds: 60
            periodSeconds: 20
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: core-crm-service
  namespace: crm-system
spec:
  selector:
    app: core-crm
  ports:
    - port: 8084
      targetPort: 8084
  type: ClusterIP