apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  namespace: crm-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: notification:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service:9092"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgresql-notification:5432/notification_db"
            - name: SPRING_DATASOURCE_USERNAME
              value: "notification_user"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "notification_password"
            - name: KAFKA_TOPIC_MAIN
              value: "notifications"
            - name: KAFKA_TOPIC_DLT
              value: "notifications.DLT"
            - name: KAFKA_CONSUMER_GROUP_ID
              value: "notification-group"
            - name: SERVER_PORT
              value: "8085"
          livenessProbe:
            exec:
              command: ["sh", "-c", "echo 'Liveness check'"]
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["sh", "-c", "echo 'Readiness check'"]
            initialDelaySeconds: 30
            periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: crm-system
spec:
  selector:
    app: notification
  ports:
    - port: 8085
      targetPort: 8085
  type: ClusterIP