apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  namespace: crm-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: notification:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8085
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service:9092"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgresql-notification-service:5432/notification_db"
            - name: SPRING_DATASOURCE_USERNAME
              value: "notification_user"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "notification_password"
            - name: KAFKA_TOPIC_MAIN
              value: "notifications"
            - name: KAFKA_TOPIC_DLT
              value: "notifications.DLT"
            - name: KAFKA_CONSUMER_GROUP_ID
              value: "notification-group"
            - name: SERVER_PORT
              value: "8085"
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8085
            initialDelaySeconds: 90
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8085
            initialDelaySeconds: 60
            periodSeconds: 20
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: crm-system
spec:
  selector:
    app: notification
  ports:
    - port: 8085
      targetPort: 8085
  type: ClusterIP