apiVersion: apps/v1
kind: Deployment
metadata:
  name: price-history
  namespace: crm-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: price-history
  template:
    metadata:
      labels:
        app: price-history
    spec:
      containers:
        - name: price-history
          image: price-history:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service:9092"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgresql-history-service:5432/history_db"
            - name: SPRING_DATASOURCE_USERNAME
              value: "history_user"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "history_password"
            - name: KAFKA_TOPIC_RAW_ESTATE_DATA
              value: "raw-estate-data"
            - name: KAFKA_CONSUMER_GROUP_ID
              value: "price-history-group"
            - name: SERVER_PORT
              value: "8083"
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 90
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8083
            initialDelaySeconds: 60
            periodSeconds: 20
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: price-history-service
  namespace: crm-system
spec:
  selector:
    app: price-history
  ports:
    - port: 8083
      targetPort: 8083
  type: ClusterIP