spring:
  application:
    name: content-processor
  datasource:
    crm:
      url: jdbc:postgresql://localhost:5432/crm_db
      username: crm_user
      password: crm_password
    history:
      url: jdbc:postgresql://localhost:5433/history_db
      username: history_user
      password: history_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: estate-group
      trusted-package: com.petrov.content_loader_adapter.dto
      auto-commit: false
      auto-offset-reset: earliest
      max-poll-records: 500
      fetch-max-bytes: 52428800 #50mb

server:
  port: 8081

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html