spring:
  application:
    name: content-processor

  datasource:
    url: jdbc:postgresql://localhost:5433/history_db
    username: history_user
    password: history_password

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 1000
        order_inserts: true
        order_updates: true
        generate_statistics: true
        connection:
          provider_disables_autocommit: true

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

  kafka:
    bootstrap-servers: localhost:29092
    topic: raw-estate-data
    consumer:
      group-id: content-processor-group
      trusted-package: com.petrov.content_processor.dto
      auto-commit: false
      auto-offset-reset: earliest
      max-poll-records: 500
      fetch-max-bytes: 52428800 #50mb

server:
  port: 8082

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.petrov.content_processor: DEBUG
    org.springframework.kafka: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

app:
  batch:
    chunk-size: 1000
    retry:
      max-attempts: 3
      backoff:
        initial-interval: 1000
        multiplier: 2.0